apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rajatjindal-goodfirstissue-slack
  namespace: openfaas-fn
spec:
  encryptedData:
    slack.yaml: AgBRGU9CbOn0ZJ9tLyl5GpJqiakh1aAJf6dNabnubih2rhDwwvsnJEXhBpq8AWob+eaFN5cBNM/g54G1IveDq6G76zWVbqg5UKocI3Oes7AgNuVffNZdXU1uJ5moi3vmw4+TrZ8hTZOGR0wq5K1a+9u8Zltr4I+4hjvhjd83W0T/naLtzyOpZZch2LvNw98BgqTarWzf9GiKNMqYnZEjR+5snX9eZPuX515e+K+3W2hbYGyGrqM+j9Sc7oJttZEQON2L4pzm1kGWmdJf4w/RC4FFJyGf/tpZj29qGecsPtvf+5WUB6Pa5C8Zrvqc94DXUtuZIztaoQl4wdGHLiKS1sBfJqeRk3aZEkqEpYiyu/jp0z49otvCG2emefq6K48U5EEoVkRnmi7RPOFN3amMZR9RaNia2uNcv5Avj3shGyweFxnOXYRgLQQl3uycvY2jsSRKIzWCSw21IkqnPmMtaZtQV8rhHFu9yscgUAQGL3V3+AvYc5t9XniRyFVqXaHgvpD4g0URE762XmIRRNKIGOyXO6rUeaBCovImjctfa5Ewo3nTmLA4eFuvphdUNsM+JhZAUoAYCN//eOXfPwIo5V/fEG3ZCY1gDdMwhE2FkHSqdFDhkIfhyWvkgKR6Y06zfS9nZFj+Azjrk6C4PihQdLvHgtrMVAHrBmfAqVmuGm4TeQyqMDzF8T8pyae9ov2JvWitITlH09YpccKie/R98AbqVO7yEqghpXi5NkhJTz0dOLe01NL7ZsQrnsozFtuqucakCilN/H/pjTEw0b7cN/GvievL6WJix8FX/x11sQy2yq+yI6VrDKE+

